from typing import Protocol
from ipo_risk.schemas import IPOAnalysisResult
class AnalysisRepository(Protocol):
    def save(self, result: IPOAnalysisResult) -> None: ...
    def get(self, analysis_id: str) -> IPOAnalysisResult | None: ...
